name: Deploy .NET Docker App to Ubuntu

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build -t myapp:latest .

    - name: Save Docker image to tar file
      run: |
        docker save myapp:latest -o myapp.tar

    - name: Upload image to server via SCP
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: "myapp.tar"
        target: "/home/${{ secrets.SERVER_USER }}/"

    - name: Load & Run Docker image on server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          docker stop myapp || true
          docker rm myapp || true
          docker load -i myapp.tar
          docker run -d --name myapp -p 80:80 myapp:latest
